## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(columns=['EIN', 'NAME'])

In [ ]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
app_valuecounts = application_df['APPLICATION_TYPE'].value_counts()
app_valuecounts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = app_valuecounts[app_valuecounts < 1000].index
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
Other     2266
T4        1542
T6        1216
T5        1173
T19       1065
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
class_valuecounts = application_df['CLASSIFICATION'].value_counts()
class_valuecounts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_valuecounts[class_valuecounts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = class_valuecounts[class_valuecounts < 1000].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
application_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,AFFILIATION_CompanySponsored,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,1,0,0,0,1,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [ ]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = application_df['IS_SUCCESSFUL']
X = application_df.drop(columns = 'IS_SUCCESSFUL')
# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=89)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
input_features = len(X_train_scaled[0])
layer_1 = 80
layer_2 = 40
layer_3 = 20
nn_model = tf.keras.models.Sequential()



# First hidden layer
#  YOUR CODE GOES HERE
nn_model.add(tf.keras.layers.Dense(units=layer_1, activation="relu", input_dim= input_features))

# Second hidden layer
#  YOUR CODE GOES HERE
nn_model.add(tf.keras.layers.Dense(units=layer_2, activation="relu"))

# Output layer
#  YOUR CODE GOES HERE
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))
# Check the structure of the model
nn_model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 80)                3280

 dense_4 (Dense)             (None, 40)                3240

 dense_5 (Dense)             (None, 1)                 41

=================================================================
Total params: 6561 (25.63 KB)
Trainable params: 6561 (25.63 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
#  YOUR CODE GOES HERE
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
from keras.src.saving.saving_lib import save_weights_only
from keras.src.saving.saving_api import save_weights
import os
from tensorflow.keras.callbacks import ModelCheckpoint

os.makedirs('checkpoints1/',exist_ok = True)
file_path = "checkpoints1/weights.{epoch:02d}.hdf5"

callback = ModelCheckpoint(filepath = file_path, save_weights_only = True, period = 5)

WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.

In [ ]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=50, callbacks = [callback])

Epoch 1/50
804/804 [==============================] - 3s 2ms/step - loss: 0.5753 - accuracy: 0.7182
Epoch 2/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5628 - accuracy: 0.7244
Epoch 3/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5586 - accuracy: 0.7268
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5574 - accuracy: 0.7274
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5558 - accuracy: 0.7289
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5549 - accuracy: 0.7287
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5544 - accuracy: 0.7292
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5536 - accuracy: 0.7296
Epoch 9/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5524 - accuracy: 0.7310
Epoch 10/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5519 - accuracy: 0.7297
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5512 - accuracy: 0.7301
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5520 - accuracy: 0.7312
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5510 - accuracy: 0.7313
Epoch 14/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5509 - accuracy: 0.7315
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5508 - accuracy: 0.7322
Epoch 16/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5501 - accuracy: 0.7327
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5501 - accuracy: 0.7327
Epoch 18/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5494 - accuracy: 0.7321
Epoch 19/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5495 - accuracy: 0.7324
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7332
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5491 - accuracy: 0.7332
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5485 - accuracy: 0.7329
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5482 - accuracy: 0.7336
Epoch 24/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5479 - accuracy: 0.7330
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5478 - accuracy: 0.7334
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5479 - accuracy: 0.7335
Epoch 27/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5478 - accuracy: 0.7340
Epoch 28/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5469 - accuracy: 0.7335
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5467 - accuracy: 0.7341
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5472 - accuracy: 0.7346
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7343
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7341
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7343
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5468 - accuracy: 0.7343
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7341
Epoch 36/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5456 - accuracy: 0.7346
Epoch 37/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5458 - accuracy: 0.7338
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7342
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7336
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7343
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7348
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7351
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7347
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7350
Epoch 45/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5445 - accuracy: 0.7348
Epoch 46/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5450 - accuracy: 0.7346
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5448 - accuracy: 0.7352
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7346
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7355
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5446 - accuracy: 0.7352

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5525 - accuracy: 0.7380 - 483ms/epoch - 2ms/step
Loss: 0.5524641871452332, Accuracy: 0.7379592061042786

In [ ]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn_model.save("alphebetsoupcharity1.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

# New Section

In [ ]:
#from google.colab import drive
#drive.mount('/Colab Notebooks/drive')

In [ ]:
from google.colab import files
import shutil

shutil.make_archive("checkpoints1", "zip", "checkpoints1")
files.download("checkpoints1.zip")
# files.download("alphebetsoupcharity1.h5")